# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HttpPing < Formula
  desc "Http-Ping is similar to the usual ping networking utility but instead of working on top of ICMP, it works on top of HTTP/S."
  homepage "Http-Ping is similar to the usual ping networking utility but instead of working on top of ICMP, it works on top of HTTP/S."
  version "1.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fever-ch/http-ping/releases/download/v1.2.1/http-ping_1.2.1_darwin_arm64.tar.gz"
      sha256 "11307447bbd45986fd5f9ce62dfc2929d55da0d74d8b6d56b3f324b8a5512b5e"

      def install
        bin.install "http-ping"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fever-ch/http-ping/releases/download/v1.2.1/http-ping_1.2.1_darwin_amd64.tar.gz"
      sha256 "347d7225bea23e94dda12947b76f97d50a10c2202bd734ac561249ee14d81eb2"

      def install
        bin.install "http-ping"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fever-ch/http-ping/releases/download/v1.2.1/http-ping_1.2.1_linux_arm64.tar.gz"
      sha256 "a7cfe545449eefd5f3f49ef7dbc10083af3cd604b97cd60ca8082fab280cf1ba"

      def install
        bin.install "http-ping"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fever-ch/http-ping/releases/download/v1.2.1/http-ping_1.2.1_linux_amd64.tar.gz"
      sha256 "56711eef063bfd6e3ee925e7bab9ad1e44ef693ca16924b4245ded2140ca48fd"

      def install
        bin.install "http-ping"
      end
    end
  end
end
