# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HttpPing < Formula
  desc "Http-Ping is similar to the usual ping networking utility but instead of working on top of ICMP, it works on top of HTTP/S."
  homepage "Http-Ping is similar to the usual ping networking utility but instead of working on top of ICMP, it works on top of HTTP/S."
  version "1.2.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fever-ch/http-ping/releases/download/v1.2.3/http-ping_1.2.3_darwin_arm64.tar.gz"
      sha256 "6664811a9303aff99387c0812f611a3fa234b58ff24a988fe28a3781e3336e36"

      def install
        bin.install "http-ping"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fever-ch/http-ping/releases/download/v1.2.3/http-ping_1.2.3_darwin_amd64.tar.gz"
      sha256 "ad21eb82314554133ea0768ed8b4d1159fad2d812209c90bfafcb414623f94a7"

      def install
        bin.install "http-ping"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fever-ch/http-ping/releases/download/v1.2.3/http-ping_1.2.3_linux_amd64.tar.gz"
      sha256 "1eda7928758ddc2fafc19207937f1925c4b0fd128ab28fada620a7290f6abeab"

      def install
        bin.install "http-ping"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fever-ch/http-ping/releases/download/v1.2.3/http-ping_1.2.3_linux_arm64.tar.gz"
      sha256 "577b30fdc509c65694f79ec490bbcf7e57bfd24a0600c46dbb4ca0779176d66a"

      def install
        bin.install "http-ping"
      end
    end
  end
end
